// Replace each `art` class with an image URL by adding `thumbnail` and `media`.
// The renderer will automatically prefer real media when provided.
window.PROJECTS = [
  { slug:'m37-distorted-index', title:'M37 / Distorted Index', category:'graphics', year:'2025', thumbnail:'media/m37-distorted-index.png', media:'media/m37-distorted-index.png', alt:'Experimental yellow and black typographic composition with distorted columns of Swedish text', aspectRatio:'16 / 9', size:'wide', featured:true, description:'Experimental graphic composition.' },
  { slug:'kronofogden', title:'Kronofogden', category:'worlds', year:'2026', thumbnail:'media/kronofogden-character.png', media:'media/kronofogden-character.png', alt:'Full-length character artwork of Kronofogden in a dark industrial interior', aspectRatio:'4 / 5', size:'tall', featured:true, description:'Character and worldbuilding study.' },
  { slug:'neon-apparition', title:'Neon Apparition', category:'photo', year:'2026', thumbnail:'media/cara/cara-01.jpg', media:'media/cara/cara-01.jpg', alt:'Red interior with a cyan projected figure and silhouetted plant', aspectRatio:'4 / 3', size:'standard', description:'Light and projection study. Imported from Cara.' },
  { slug:'creature-study', title:'Creature Study', category:'graphics', year:'2026', thumbnail:'media/creature-study.png', media:'media/creature-study.png', alt:'Textured illustrated creature portrait with large eyes against a dark ground', aspectRatio:'2 / 3', size:'tall', description:'Illustrated character study.' },
  { slug:'flode', title:'flöde~', category:'uxui', year:'2026', meta:'(Max/Msp, m4l, VST, Standalone)', thumbnail:'media/flode/flode-six-channel-logo-large.png', media:['media/flode/flode-six-channel-logo-large.png','media/flode/flode-pod-design.png','media/flode/flode-orange-interface.png','media/flode/flode-hardware-render.png'], alt:'Flöde six-channel sampler and generative sequencer interface', aspectRatio:'3 / 2', size:'wide', intro:{ name:'flöde~', lead:'a living modular instrument for sound manipulation built in Max/MSP and m4l (Ableton) but also a standalone version for both Windows and Mac OS systems.', question:'In short, what is it and what does it do?', between:['a 6-channel sampler','a generative sequencer','a sound mangler','a loop machine','... and an improvisational electronic instrument'], body:'Each pod loads, plays and changes sound through speed, panning, volume, slicing, probability and controlled randomness, among other things. The pods can work independently – almost like small organisms – but are held together by a common tempo and synchronization.' }, definitions:['Modular generation — six autonomous pods reshape and interweave samples in real time.','6-channel sampling — load, loop and transform six sound sources in parallel.','Generative sequencing — evolve patterns through probability and controlled randomness.','Real-time audio mangling — reshape speed, pitch, slicing, panning and volume.','Loop-machine performance — capture and repeat material without breaking flow.','Rhythmic precision — lock every pod to a shared master clock and BPM.','Evolving soundscapes — create unpredictable textures that remain musically connected.','Open-ended instrument — use it however your creative practice demands.'], definitionClosing:'... or what you as a creative want it to be', description:'Interface, interaction and hardware concept for a six-channel sampler workstation.' },
  { slug:'lost-and-found', title:'Lost & Found', category:'photo', year:'2026', thumbnail:'media/cara/cara-03.jpg', media:'media/cara/cara-03.jpg', alt:'Illuminated Lost and Found sign photographed against darkness', aspectRatio:'4 / 3', size:'standard', description:'Night image. Imported from Cara.' },
  { slug:'mechanical-figure', title:'Mechanical Figure', category:'worlds', year:'2026', thumbnail:'media/cara/cara-04.jpg', media:'media/cara/cara-04.jpg', alt:'Tall biomechanical character with an oval riveted body against black', aspectRatio:'2 / 3', size:'tall', featured:true, description:'Character and object study. Imported from Cara.' },
  { slug:'chrome-distortion', title:'Chrome Distortion', category:'graphics', year:'2026', thumbnail:'media/cara/cara-05.jpg', media:'media/cara/cara-05.jpg', alt:'Distorted chrome forms and fragmented typography in a dark composition', aspectRatio:'75 / 106', size:'standard', description:'Experimental graphic composition. Imported from Cara.' },
  { slug:'creature-turnaround', title:'Karaktärer 1-3', category:'worlds', year:'2026', thumbnail:'media/cara/cara-06.jpg', media:'media/cara/cara-06.jpg', alt:'Front side and rear views of an orange-backed creature design', aspectRatio:'3 / 2', size:'wide', description:'Creature design turnaround. Imported from Cara.' },
  { slug:'aao', title:'ÄÄO', category:'print', year:'2026', thumbnail:'media/cara/cara-08.jpg', media:'media/cara/cara-08.jpg', alt:'Toothbrush package concept with bold black typography on translucent orange', aspectRatio:'2 / 3', size:'tall', description:'Packaging and type study. Imported from Cara.' },
  { slug:'papa-tom-yoga', title:'Papa Tom Yoga', category:'print', year:'2026', thumbnail:'media/cara/cara-09.jpg', media:'media/cara/cara-09.jpg', alt:'Blue cassette cover design with a portrait and vertical serif type', aspectRatio:'1 / 1', size:'standard', description:'Release artwork. Imported from Cara.' },
  { slug:'magenta-field', title:'Magenta Field', category:'photo', year:'2026', thumbnail:'media/cara/cara-10.jpg', media:'media/cara/cara-10.jpg', alt:'Abstract magenta and violet close-up with soft granular texture', aspectRatio:'1 / 1', size:'standard', description:'Abstract image study. Imported from Cara.' }
];
